#! /usr/bin/env python3

import os
import requests

source_directory= '/data/feedback'
url = 'http://34.170.151.93/feedback/'
comment = {}
file_list = os.listdir(source_directory)
#print(file_list)
for file in file_list:
        with open(source_directory+'/'+file, 'r') as comment_file:
                comment['title']=comment_file.readline()
                comment['name']=comment_file.readline()
                comment['date']=comment_file.readline()
                comment['feedback']=comment_file.readlines()
                #print(comment)
                response = requests.post(url, data=comment)
                response.raise_for_status()

